export const MajorAirlines = [
    { name: "Air Canada", code: "ACA", region: "North America", logoFile: "AirCanada.png", logoScale: 1.16 },
    { name: "WestJet", code: "WJA", region: "North America", logoFile: "WestJet.png", logoScale: 1.22 },
    { name: "Air Transat", code: "TSC", region: "North America", logoFile: "AirTransit.png", logoScale: 1.18 },
    { name: "American Airlines", code: "AAL", region: "North America", logoFile: "AmericanAirlines.png", logoScale: 1.12 },
    { name: "Delta Air Lines", code: "DAL", region: "North America", logoFile: "Delta.png", logoScale: 1.18 },
    { name: "United Airlines", code: "UAL", region: "North America", logoFile: "UnitedAirlines.png", logoScale: 1.14 },
    { name: "JetBlue", code: "JBU", region: "North America", logoFile: "JetBlue.png", logoScale: 1.16 },
    { name: "Alaska Airlines", code: "ASA", region: "North America", logoFile: "AlaskaAirlines.png", logoScale: 1.16 },
    { name: "Southwest Airlines", code: "SWA", region: "North America", logoFile: "SouthWest.png", logoScale: 1.18 },
    { name: "Air France", code: "AFR", region: "Europe", logoFile: "AirFrance.png", logoScale: 1.14 },
    { name: "British Airways", code: "BAW", region: "Europe", logoFile: "BritishAirways.png", logoScale: 1.22 },
    { name: "Lufthansa", code: "DLH", region: "Europe", logoFile: "Lufthansa.png", logoScale: 1.16 },
    { name: "KLM", code: "KLM", region: "Europe", logoFile: "KLM.png", logoScale: 1.14 },
    { name: "Swiss", code: "SWR", region: "Europe", logoFile: "Swiss.png", logoScale: 1.14 },
    { name: "Iberia", code: "IBE", region: "Europe", logoFile: "Iiberia.png", logoScale: 1.2 },
    { name: "Aer Lingus", code: "EIN", region: "Europe", logoFile: "AerLingus.png", logoScale: 1.14 },
    { name: "Turkish Airlines", code: "THY", region: "Europe", logoFile: "TurkishAirlines.png", logoScale: 1.16 },
    { name: "TAP Air Portugal", code: "TAP", region: "Europe", logoFile: "TAP.png", logoScale: 1.14 },
    { name: "SAS", code: "SAS", region: "Europe", logoFile: "SAS.png", logoScale: 1.16 },
    { name: "Virgin Atlantic", code: "VIR", region: "Europe", logoFile: "VirginAtlantic.png", logoScale: 1.22 },
    { name: "Finnair", code: "FIN", region: "Europe", logoFile: "Finnair.png", logoScale: 1.14 },
    { name: "ITA Airways", code: "ITY", region: "Europe", logoFile: "ITA.png", logoScale: 1.2 },
    { name: "Air China", code: "CCA", region: "Asia", logoFile: "AirChina.png", logoScale: 1.14 },
    { name: "China Eastern Airlines", code: "CES", region: "Asia", logoFile: "ChinaEastern.png", logoScale: 1.14 },
    { name: "China Southern Airlines", code: "CSN", region: "Asia", logoFile: "ChinaSouthern.png", logoScale: 1.16 },
    { name: "All Nippon Airways", code: "ANA", region: "Asia", logoFile: "ANA.png", logoScale: 1.18 },
    { name: "Japan Airlines", code: "JAL", region: "Asia", logoFile: "JapanAirlines.png", logoScale: 1.16 },
    { name: "Singapore Airlines", code: "SIA", region: "Asia", logoFile: "SingaporeAirlines.png", logoScale: 1.16 },
    { name: "Cathay Pacific", code: "CPA", region: "Asia", logoFile: "CathayPacific.png", logoScale: 1.16 },
    { name: "Korean Air", code: "KAL", region: "Asia", logoFile: "KoreanAir.png", logoScale: 1.16 },
    { name: "Emirates", code: "UAE", region: "Middle East", logoFile: "Emirates.png", logoScale: 1.16 },
    { name: "Qatar Airways", code: "QTR", region: "Middle East", logoFile: "QatarAirways.png", logoScale: 1.16 },
    { name: "Etihad Airways", code: "ETD", region: "Middle East", logoFile: "EithadAirways.png", logoScale: 1.18 },
    { name: "Saudia", code: "SVA", region: "Middle East", logoFile: "Saudia.png", logoScale: 1.16 },
    { name: "Qantas", code: "QFA", region: "Oceania", logoFile: "Qantas.png", logoScale: 1.16 },
    { name: "LATAM Airlines", code: "LAN", region: "South America", logoFile: "LatamAirlines.png", logoScale: 1.16 },
    { name: "Avianca", code: "AVA", region: "South America", logoFile: "Avianca.png", logoScale: 1.16 },
    { name: "South African Airways", code: "SAA", region: "Africa", logoFile: "SouthAfrican.png", logoScale: 1.16 },
    { name: "Thai Airways", code: "THA", region: "Asia", logoFile: "Thai.png", logoScale: 1.18 },
    { name: "Hawaiian Airlines", code: "HAL", region: "North America", logoFile: "HawaiianAIrlines.png", logoScale: 1.2 }
];

const majorAirlinesByCode = new Map(MajorAirlines.map((airline) => [airline.code, airline]));

const weightedMajorAirlineCodes = [
    "ACA",
    "ACA",
    "WJA",
    "WJA",
    "TSC",
    "AAL",
    "AAL",
    "DAL",
    "DAL",
    "UAL",
    "UAL",
    "JBU",
    "ASA",
    "SWA",
    "AFR",
    "AFR",
    "BAW",
    "BAW",
    "DLH",
    "DLH",
    "DLH",
    "DLH",
    "DLH",
    "KLM",
    "KLM",
    "SWR",
    "SWR",
    "IBE",
    "EIN",
    "THY",
    "TAP",
    "SAS",
    "VIR",
    "FIN",
    "ITY",
    "CCA",
    "CES",
    "CSN",
    "ANA",
    "JAL",
    "SIA",
    "CPA",
    "KAL",
    "UAE",
    "QTR",
    "ETD",
    "SVA",
    "QFA",
    "LAN",
    "AVA",
    "SAA",
    "THA",
    "HAL"
];

export const WeightedMajorAirlines = weightedMajorAirlineCodes
    .map((code) => majorAirlinesByCode.get(code))
    .filter(Boolean);